services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIRECTORY}/telegram-bot:/app/data
    ports:
      - "9091:9091"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ALLOWED_USERS: ${ALLOWED_USERS}
      ALERTS_PORT: "9091"
      ALERTS_CHAT_ID: ${ALERTS_CHAT_ID:-}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
